### ISSUE TITLE
Java Backend

### ISSUE THREAD

**Issue by ajaku** [dantsar/SoundClown#2]
Considering the existing PostgreSQL database setup on `fred13kim/setup-db` will be working on developing the back-end Java interface using the [JDBC API](https://docs.oracle.com/javase/8/docs/technotes/guides/jdbc/).

**Comment by ajaku** [comment]
Switched to JPA.

**Comment by hfzi** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
cheukw, @DavidDerhy, @jinzhi2020, @jonathanmendes, @megachilles2018, @gustavoparedes1978, @sharpeyesizz, @billni, @Alan-Penkar, @Fredjet, @fuwensun, @pmarches, @jorgeborges, @CreatorMetaSky, @dariuskasperavicius, @zero1ne, @Fayadh56, @abetomo, @JoyPanda, @SpotLabsNET, @unforgiven512, @marcsnts, @dpitic, @Fiber-Man, @niepiekm, @lyricjin, @tcook4, @christopherwoo, @ujinyng, @erwinwolff, @iosifvilcea, @wemeetagain, @XatMassacrE, @product-think2049, @Jisen, @ruivalentemaia, @mreeves1, @TZJ1997, @tjordy17, @supanadit, @Earthwater, @kSpacer201, @tyosuke, @a07z, @PabloAprende, @schwmr, @vyorkin, @GRAYCN, @aviggiano, @airuowuhen
