### ISSUE TITLE
Springboot is creating tables without foreign keys

### ISSUE THREAD

**Issue by fred13kim** [dantsar/SoundClown#20]
Issues:
- On first build, springboot is creating tables if database is empty (odd behavior, need to check where this is happening)
- Tables created are created with columns and not foreign keys.

**Comment by ajaku** [comment]
Issue was that using JPA annotations was causing the database to be recreated locally with the constraints defined in Users, Tracks and Playlists.java. Fixed the issue by adding constraints as annotations.
